[package]
name = "rust_in_peace"
version = "0.1.0"
edition = "2021"


[dependencies]
clearscreen = "2.0.1"
regex = "1.8.1"
serde = { version = "1.0", features = ["derive"]}
ron = "0.8.0"
rand = "0.8.5"

[lib]
name = "game_lib"
path = "src/game_lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
